name: inno_cluster

services:
  mysql1:
    image: mysql:8.0
    container_name: mysql1
    environment: { MYSQL_ROOT_PASSWORD: "1234" }
    command: ["--server-id=100", "--enforce-gtid-consistency=ON", "--gtid-mode=ON"]

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    environment: { MYSQL_ROOT_PASSWORD: "1234" }
    command: ["--server-id=101", "--enforce-gtid-consistency=ON", "--gtid-mode=ON"]

  mysql3:
    image: mysql:8.0
    container_name: mysql3
    environment: { MYSQL_ROOT_PASSWORD: "1234" }
    command: ["--server-id=102", "--enforce-gtid-consistency=ON", "--gtid-mode=ON"]

  # 첫 번째 라우터 (기본 6446, 6447 포트)
  router1:
    image: mysql/mysql-router:8.0
    container_name: router1
    environment:
      MYSQL_HOST: mysql1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: "1234"
      MYSQL_CREATE_ROUTER_USER: 0
    ports:
      - "6446:6446"
      - "6447:6447"
    depends_on: [mysql1, mysql2, mysql3]

  # 두 번째 라우터 (보조 7446, 7447 포트)
  router2:
    image: mysql/mysql-router:8.0
    container_name: router2
    environment:
      MYSQL_HOST: mysql1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: "1234"
      MYSQL_CREATE_ROUTER_USER: 0
    ports:
      - "7446:6446"
      - "7447:6447"
    depends_on: [mysql1, mysql2, mysql3]