events { 
    worker_connections 1024; 
}

http {
    # 톰캣 2대로 트래픽 분산 및 세션 유지(ip_hash)
    upstream tomcat-servers {
        server host.docker.internal:8080;
        server host.docker.internal:8090;
    }

    server {
        listen 80;
        server_name localhost;

        # 정적 리소스는 Nginx가 직접 제공 (톰캣 부하 감소)
        location /project/ {
            alias /usr/share/nginx/html/;
            index index.html;
            expires 7d;
            add_header Cache-Control "public";
        }

        # API 요청만 톰캣으로 전달
        location /project/api/ {

            proxy_pass http://tomcat-servers;

            # 원본 클라이언트 정보를 톰캣에 전달
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}