events { 
    worker_connections 1024; 
}

http {
    # 톰캣 2대로 트래픽 분산 및 세션 유지(ip_hash)
    upstream tomcat-servers {
        ip_hash; 
        server 127.0.0.1:8080;
        server 127.0.0.1:8090;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://tomcat-servers;
        }
    }
}